# Site settings
title: EIS Icicle Demo
email: scott.keller13@gmail.com
description: "Mock up of using an Icicle chart to make and interactive Source/Fund page."
baseurl: "/jsfiddles-eis-icicle"
url: "http://sskeller.github.io"

# Build settings
markdown: kramdown
permalink: pretty
