# Site settings
<<<<<<< HEAD
title: Base Fiddle (EIS)
email: scott.keller13@gmail.com
description: "Base Fiddle with Modernizr, jQuery, Lodash, Less"
baseurl: "/jsfiddles-base-eis"
=======
title: EIS Icicle Demo
email: scott.keller13@gmail.com
description: "Mock up of using an Icicle chart to make and interactive Source/Fund page."
baseurl: "/jsfiddles-eis-icicle"
>>>>>>> master
url: "http://sskeller.github.io"

# Build settings
markdown: kramdown
permalink: pretty
